server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://\:\/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000

spring:
  application:
    name: eureka-server

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
